### PR TITLE
feat(CVSS2, CVSS3): add methods to fetch isolated temporal and environmental vectors

### PR DESCRIPTION
**Pull request by fqlenos**
This Pull Request introduces an enhanced feature that allows users to fetch isolated Temporal and Environmental CVSS vectors specifically for both CVSS version 2.0 and the 3.X series. 

The isolated vectors provide a more granular view of vulnerabilities by separating the base metrics from the Temporal and Environmental metrics.

Additionally, the unit tests have been modified to ensure that these changes are properly implemented and validated.

### CODE REVIEW

**Comment by fqlenos** [comment]
In the case of accepting this feature, would it be possible to generate a new release of the library with the latest changes applied so far?

Thanks in advance :)

**Review by jsvob — APPROVED** [review]
LGTM, thank you for the contribution! I'll let @jobselko review too since I'm not familiar with the project as much as I'd like.

**Comment by jobselko** [comment]
Hi, I am sorry for the delay. I will look into it next week.

**Review by jobselko — APPROVED** [review]
I would prefer to separate commits by version so that each commit contains code and tests for the given version, but otherwise, LGTM!

**Comment by fqlenos** [comment]
@jobselko sure! I have no problem with doing it in two parts :)
Thank you all!

**Comment by skontar** [comment]
@fqlenos we have another update to CVSS v4.0 rounding worked on, so expect release afterwards.

**Pull request merged**
